// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
// By considering the terms in the fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let sequence = [1, 2];
let sumOfEvens = 0;
// sequence will be an array with the 2 starting numbers
function fibonacci() {
  let num1 = sequence[0];
  let num2 = sequence[1];
  let nextInSequence = 3;

  while (nextInSequence < 4000000) {
    console.log(`Is ${nextInSequence} < 4,000,000?`);
    // get the nextInSequence number by adding the previous two
    nextInSequence = num1 + num2;
    // reassign num1 and num2 to reflect new value in sequence
    num1 = num2;
    num2 = nextInSequence;

    sequence.push(nextInSequence);
  }
}

fibonacci();

function getSum() {
  for (value of sequence) {
    if (value % 2 === 0) {
      sumOfEvens += value
    }
  }
  return sumOfEvens
}